### ISSUE TITLE
Add Python 3.5 to tox and trove classifiers

### ISSUE THREAD

**Issue by markrwilliams** [twisted/constantly#22]
We test against Python 3.5:

https://github.com/twisted/constantly/blob/3189c1b4913565caf6280213e2b09e503f7ef148/.travis.yml#L4-L9

But we don't have an explicit `tox` enviroment for it:

https://github.com/twisted/constantly/blob/3189c1b4913565caf6280213e2b09e503f7ef148/tox.ini#L2

Or a trove classifier:

https://github.com/twisted/constantly/blob/3189c1b4913565caf6280213e2b09e503f7ef148/setup.py#L21-L32

`constantly` should have both a Python 3.5 `tox` environment and trove classifier.

**Comment by markrwilliams** [comment]
See https://github.com/twisted/constantly/pull/21#discussion_r161062214

**Comment by alex** [comment]
OBE, but also fixed.
