### ISSUE TITLE
fix broken release infrastructure

### ISSUE THREAD

**Issue by glyph** [twisted/constantly#40]
I've been trying to get the tag workflow to run for the last hour or so and it seems broken in several ways. Here's the most recent failure:

https://github.com/twisted/constantly/actions/runs/6679755558/job/18152162563

I'm just going to make a release manually now.

**Comment by adiroiban** [comment]
I see that PyPi is configuredf for ci.yml , while the current file is named ci.yaml

This was previously configured

![image](https://github.com/twisted/constantly/assets/204609/279a530a-9dd3-4e0d-8878-4cc404b7b4ab)


-------

I have reconfigured PyPI for ci.yaml

This is what is configured now

![image](https://github.com/twisted/constantly/assets/204609/ff45c805-a585-4a2f-98cf-6503d70be198)

**Comment by glyph** [comment]
@adiroiban cool. do you want to try doing a no-op micro-version release just to see if this works?

**Comment by adiroiban** [comment]
I can try do a .dev0 release on https://test.pypi.org/ .... not sure how the versioner part works for testing :( ... but I will give it at try.
